# Generated by Django 5.2 on 2025-04-06 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_name = 'users_user'
                ) THEN
                    CREATE TABLE IF NOT EXISTS users_user AS (SELECT * FROM auth_user LIMIT 0);
                    ALTER TABLE users_user ADD COLUMN "bio" text;
                    ALTER TABLE users_user ADD COLUMN "avatar" varchar(100);
                    ALTER TABLE users_user ADD COLUMN "created_at" timestamp with time zone;
                    ALTER TABLE users_user ADD COLUMN "updated_at" timestamp with time zone;
                    ALTER TABLE users_user ADD COLUMN "website" varchar(200);
                    INSERT INTO users_user(id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, bio, avatar, created_at, updated_at, website)
                    SELECT id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, '', NULL, date_joined, date_joined, '' 
                    FROM auth_user;
                END IF;
            END
            $$;
            """,
            reverse_sql="""
            -- 不需要反向操作
            """
        ),
    ]
