global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 系统指标监控 (Node Exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s

  # Docker容器监控 (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 5s

  # Django应用监控
  - job_name: 'django-app'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Nginx监控 (如果配置了nginx-exporter)
  - job_name: 'nginx'
    static_configs:
      - targets: ['host.docker.internal:9113']
    scrape_interval: 10s

  # PostgreSQL监控 (如果配置了postgres-exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['host.docker.internal:9187']
    scrape_interval: 10s

  # 自定义健康检查监控
  - job_name: 'health-checks'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/health/'
    scrape_interval: 30s 