# Generated by Django 5.2 on 2025-07-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField(blank=True, verbose_name='About页面HTML内容')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': 'About页面内容',
                'verbose_name_plural': 'About页面内容',
            },
        ),
        migrations.DeleteModel(
            name='AboutMe',
        ),
    ]
