# Generated by Django 5.2 on 2025-07-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_aboutpagecontent_delete_aboutme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpagecontent',
            options={},
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='html_content',
            field=models.TextField(blank=True, default='', verbose_name='About页面HTML源码'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
