# Generated by Django 5.2 on 2025-07-06 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_aboutprofile_aboutsummary_educationexperience_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutprofile',
            options={'verbose_name': '个人信息', 'verbose_name_plural': '个人信息'},
        ),
        migrations.AlterModelOptions(
            name='aboutsummary',
            options={'verbose_name': '专业总结', 'verbose_name_plural': '专业总结'},
        ),
        migrations.AlterModelOptions(
            name='educationcourse',
            options={'ordering': ['education', 'order'], 'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='educationexperience',
            options={'ordering': ['order', '-updated_at'], 'verbose_name': '教育经历', 'verbose_name_plural': '教育经历'},
        ),
        migrations.AlterModelOptions(
            name='educationproject',
            options={'ordering': ['education', 'order'], 'verbose_name': '教育项目', 'verbose_name_plural': '教育项目'},
        ),
        migrations.AlterModelOptions(
            name='skillgroup',
            options={'ordering': ['order'], 'verbose_name': '技能组', 'verbose_name_plural': '技能组'},
        ),
        migrations.AlterModelOptions(
            name='skillitem',
            options={'ordering': ['group', 'order'], 'verbose_name': '技能项', 'verbose_name_plural': '技能项'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['order', '-updated_at'], 'verbose_name': '工作经历', 'verbose_name_plural': '工作经历'},
        ),
        migrations.AlterModelOptions(
            name='workresponsibility',
            options={'ordering': ['experience', 'order'], 'verbose_name': '工作职责', 'verbose_name_plural': '工作职责'},
        ),
        migrations.RemoveField(
            model_name='aboutprofile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='aboutprofile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='aboutprofile',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='aboutprofile',
            name='website',
        ),
        migrations.RemoveField(
            model_name='educationproject',
            name='description',
        ),
        migrations.AddField(
            model_name='aboutprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='about_avatar', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='aboutprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='aboutprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='所在地'),
        ),
        migrations.AlterField(
            model_name='aboutprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='aboutprofile',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='头衔/职位'),
        ),
        migrations.AlterField(
            model_name='aboutsummary',
            name='content',
            field=models.TextField(verbose_name='简介内容'),
        ),
        migrations.AlterField(
            model_name='educationcourse',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='blog.educationexperience', verbose_name='教育经历'),
        ),
        migrations.AlterField(
            model_name='educationcourse',
            name='name',
            field=models.CharField(max_length=200, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='educationcourse',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='educationexperience',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='educationproject',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='blog.educationexperience', verbose_name='教育经历'),
        ),
        migrations.AlterField(
            model_name='educationproject',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='educationproject',
            name='title',
            field=models.CharField(max_length=200, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='skillgroup',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='skillitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='blog.skillgroup', verbose_name='技能组'),
        ),
        migrations.AlterField(
            model_name='skillitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='period',
            field=models.CharField(blank=True, max_length=100, verbose_name='时间段'),
        ),
        migrations.AlterField(
            model_name='workresponsibility',
            name='description',
            field=models.CharField(max_length=255, verbose_name='职责描述'),
        ),
        migrations.AlterField(
            model_name='workresponsibility',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='blog.workexperience', verbose_name='工作经历'),
        ),
        migrations.AlterField(
            model_name='workresponsibility',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
    ]
