# Generated by Django 5.2 on 2025-07-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_aboutprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workresponsibility',
            name='description',
            field=models.TextField(verbose_name='职责描述'),
        ),
    ]
