# Generated by Django 5.2 on 2025-07-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_workresponsibility_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationproject',
            name='title',
            field=models.TextField(verbose_name='项目名称'),
        ),
    ]
