# Generated by Django 5.2 on 2025-07-06 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_educationproject_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationcourse',
            options={'ordering': ['order'], 'verbose_name': '教育课程', 'verbose_name_plural': '教育课程'},
        ),
        migrations.AlterModelOptions(
            name='educationexperience',
            options={'ordering': ['order'], 'verbose_name': '教育经历', 'verbose_name_plural': '教育经历'},
        ),
        migrations.AlterModelOptions(
            name='educationproject',
            options={'ordering': ['order'], 'verbose_name': '教育项目', 'verbose_name_plural': '教育项目'},
        ),
        migrations.AlterModelOptions(
            name='skillgroup',
            options={'ordering': ['order'], 'verbose_name': '技能分组', 'verbose_name_plural': '技能分组'},
        ),
        migrations.AlterModelOptions(
            name='skillitem',
            options={'ordering': ['order'], 'verbose_name': '技能项目', 'verbose_name_plural': '技能项目'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['order'], 'verbose_name': '工作经历', 'verbose_name_plural': '工作经历'},
        ),
        migrations.AlterModelOptions(
            name='workresponsibility',
            options={'ordering': ['order'], 'verbose_name': '工作职责', 'verbose_name_plural': '工作职责'},
        ),
        migrations.RemoveField(
            model_name='aboutprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='aboutprofile',
            name='github',
            field=models.URLField(blank=True, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='aboutprofile',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='aboutprofile',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='aboutprofile',
            name='website',
            field=models.URLField(blank=True, verbose_name='个人网站'),
        ),
        migrations.AddField(
            model_name='educationproject',
            name='description',
            field=models.TextField(blank=True, verbose_name='项目描述'),
        ),
        migrations.AlterField(
            model_name='aboutprofile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='aboutprofile',
            name='location',
            field=models.CharField(max_length=100, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='aboutprofile',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='aboutprofile',
            name='title',
            field=models.CharField(max_length=100, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='aboutsummary',
            name='content',
            field=models.TextField(verbose_name='专业总结'),
        ),
        migrations.AlterField(
            model_name='educationcourse',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='blog.educationexperience'),
        ),
        migrations.AlterField(
            model_name='educationcourse',
            name='name',
            field=models.CharField(max_length=100, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='educationcourse',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='educationexperience',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='educationproject',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='blog.educationexperience'),
        ),
        migrations.AlterField(
            model_name='educationproject',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skillgroup',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skillitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='blog.skillgroup'),
        ),
        migrations.AlterField(
            model_name='skillitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='period',
            field=models.CharField(max_length=100, verbose_name='时间段'),
        ),
        migrations.AlterField(
            model_name='workresponsibility',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='blog.workexperience'),
        ),
        migrations.AlterField(
            model_name='workresponsibility',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
