# Generated by Django 5.2 on 2025-04-06 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_favorited_by_remove_post_liked_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='liked_by',
            new_name='likes',
        ),
    ]
